### ISSUE TITLE
There are two dropdown tab menus now

### ISSUE THREAD

**Issue by imdylan0831** [Alex313031/Thorium-Win-AVX2#100]
**System Details**
 - OS: Windows 11 
 - Thorium Version 116.0.5845.169 

**Problem**
This recent update duplicated the open and recently closed menu (the one with downwards arrow). Now there is an instance of it on the top left side of the screen near the tabs, and on the top right side of the screen near the minimize, resize, and close buttons.

**Screenshots**
<img width="337" alt="image" src="https://github.com/Alex313031/Thorium-Win-AVX2/assets/91943470/919d962f-65ee-406d-a4f3-c4a2816e5597">

<img width="374" alt="image" src="https://github.com/Alex313031/Thorium-Win-AVX2/assets/91943470/822abdbc-3f4e-4eef-83a4-a19c9a1dc3d1">

**Additional Notes**
This issue may have to do with me having Thorium Refresh 2023 enabled but I really like the theme so I'm sticking with it since the two tabs aren't very annoying. But I suggest putting it on the top left corner instead and remove the top right menu since it feels like smoother action to click on a section next to the tabs instead of next to the window actions. It also looks cuter for me since the button now has a border that matches the theme of browser unlike the top right one...

**Comment by gz83** [comment]
Thanks for starting this issue.

This is due to the fact that the icon in the upper right corner was not removed when the code in version 116 was frozen. In the new version, the icon in the upper right corner has been removed.

What you have to do now is to wait for Thorium to update to a version after 116, the icon in the upper right corner will disappear or temporarily close the cr23 experimental flag.

@imdylan0831
